//global object
var groceryMap = {
    tileSize: 30,
    tilesHigh: 30,
    tilesWide: 20,
    mouseX: 0,
    mouseY: 0,
    isDragging: false,
    numberOfPeople: 10
};

var map1 = [["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall"],
["wall", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "floor", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "floor", "wall"],
["wall", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "floor", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "floor", "wall"],
["wall", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "floor", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "floor", "wall"],
["wall", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "floor", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "floor", "wall"],
["wall", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "floor", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "floor", "wall"],
["wall", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "floor", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall"],
["wall", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "floor", "floor", "wall", "wall", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall", "wall", "floor", "wall"],
["wall", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "floor", "floor", "floor", "floor", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall", "wall", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall"],
["wall", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "floor", "floor", "wall", "wall", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall", "wall", "floor", "wall"],
["wall", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "floor", "floor", "floor", "floor", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall", "wall", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall"],
["wall", "floor", "floor", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "floor", "floor", "wall", "wall", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall"],
["wall", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "floor", "wall"],
["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall"]]